#!/bin/bash

clear

service_name=senti-tag-manager.service
service_dir=/etc/systemd/system
server_dir=/srv/nodejs/senti/services/tagmanager/production

service=$service_dir/$service_name

echo Registering Senti Tag Manager service for production ...


if [ ! -e "$service" ]; then
	echo
    echo "Senti Tag Manager service is not installed"
	echo "Installing Senti Tag Manager service ..."
	sudo cp $server_dir/$service_name $service_dir/$service_name
	echo "Enabling $service ..."
	sudo systemctl enable $service_name
	sudo systemctl daemon-reload
	echo "Starting $service ..."
	sudo systemctl start $service_name
else
    echo "Senti Tag Manager service is already installed"
	echo "Enabling $service ..."
	sudo systemctl enable $service_name
	sudo systemctl daemon-reload
	echo "Starting $service ..."
	sudo systemctl stop $service_name
	sudo systemctl start $service_name
fi
